#!/usr/bin/env python3
"""
Export YouTube/Google auth cookies using a saved Playwright storage state.

Usage:
  AUTH_FILE=/tmp/auth.json COOKIE_OUTPUT=/tmp/yt_cookies.txt python export_cookies.py

The AUTH_FILE must be created once manually (see README or setup instructions).
"""
import asyncio
import os
import sys


AUTH_FILE = os.environ.get("AUTH_FILE", "/tmp/auth.json")
OUTPUT_FILE = os.environ.get("COOKIE_OUTPUT", "/tmp/yt_cookies.txt")

REQUIRED_COOKIES = {"SID", "SAPISID", "__Secure-3PSID", "SSID", "APISID", "HSID"}


def to_netscape(cookies: list) -> str:
    lines = ["# Netscape HTTP Cookie File", "# Generated by export_cookies.py"]
    for c in cookies:
        domain = c["domain"]
        flag = "TRUE" if domain.startswith(".") else "FALSE"
        secure = "TRUE" if c.get("secure") else "FALSE"
        expires = str(int(c.get("expires", 0)))
        path = c.get("path", "/")
        lines.append(f"{domain}\t{flag}\t{path}\t{secure}\t{expires}\t{c['name']}\t{c['value']}")
    return "\n".join(lines) + "\n"


async def main():
    from playwright.async_api import async_playwright

    if not os.path.exists(AUTH_FILE):
        print(f"[ERROR] Auth state file not found: {AUTH_FILE}", file=sys.stderr)
        print("Run the one-time setup to generate it.", file=sys.stderr)
        sys.exit(1)

    async with async_playwright() as p:
        browser = await p.chromium.launch(headless=True)
        context = await browser.new_context(
            storage_state=AUTH_FILE,
            user_agent=(
                "Mozilla/5.0 (Windows NT 10.0; Win64; x64) "
                "AppleWebKit/537.36 (KHTML, like Gecko) "
                "Chrome/124.0.0.0 Safari/537.36"
            ),
        )
        page = await context.new_page()

        print("Navigating to YouTube...")
        await page.goto("https://www.youtube.com", wait_until="domcontentloaded", timeout=30000)
        await page.wait_for_timeout(3000)

        all_cookies = await context.cookies(
            ["https://www.youtube.com", "https://google.com", "https://accounts.google.com"]
        )

        # Verify we have auth cookies
        found = {c["name"] for c in all_cookies if c["name"] in REQUIRED_COOKIES}
        if not found:
            print("[ERROR] No auth cookies found — session may have expired.", file=sys.stderr)
            await browser.close()
            sys.exit(1)

        print(f"Found auth cookies: {', '.join(found)}")

        # Keep only YouTube and Google domain cookies
        yt_cookies = [
            c for c in all_cookies
            if any(domain in c["domain"] for domain in [".youtube.com", ".google.com", "accounts.google.com"])
        ]

        netscape = to_netscape(yt_cookies)
        with open(OUTPUT_FILE, "w", encoding="utf-8") as f:
            f.write(netscape)

        print(f"Exported {len(yt_cookies)} cookies -> {OUTPUT_FILE}")
        await browser.close()


asyncio.run(main())
